
export const Nationalites = [
    { "label": "Ivoirienne", "value": "CI", "flag": "🇨🇮" },
  { "label": "Malienne", "value": "ML", "flag": "🇲🇱" },
  { "label": "Nigériane", "value": "NG", "flag": "🇳🇬" },
  { "label": "Sénégalaise", "value": "SN", "flag": "🇸🇳" },
  { "label": "Béninoise", "value": "BJ", "flag": "🇧🇯" },
  { "label": "Burkinabè", "value": "BF", "flag": "🇧🇫" },
  { "label": "Cap-verdienne", "value": "CV", "flag": "🇨🇻" },
  { "label": "Gambienne", "value": "GM", "flag": "🇬🇲" },
  { "label": "Ghanéenne", "value": "GH", "flag": "🇬🇭" },
  { "label": "Guinéenne", "value": "GN", "flag": "🇬🇳" },
  { "label": "Guinéenne Bissau", "value": "GW", "flag": "🇬🇼" },
  { "label": "Mauritanienne", "value": "MR", "flag": "🇲🇷" },
  { "label": "Nigérienne", "value": "NE", "flag": "🇳🇪" },
  { "label": "Sierra Léonaise", "value": "SL", "flag": "🇸🇱" },
  { "label": "Togolaise", "value": "TG", "flag": "🇹🇬" },
  { "label": "Libérienne", "value": "LR", "flag": "🇱🇷" },
  { "label": "Afghane", "value": "AF", "flag": "🇦🇫" },
  { "label": "Albanaise", "value": "AL", "flag": "🇦🇱" },
  { "label": "Algérienne", "value": "DZ", "flag": "🇩🇿" },
  { "label": "Allemande", "value": "DE", "flag": "🇩🇪" },
  { "label": "Américaine", "value": "US", "flag": "🇺🇸" },
  { "label": "Angolaise", "value": "AO", "flag": "🇦🇴" },
  { "label": "Argentine", "value": "AR", "flag": "🇦🇷" },
  { "label": "Arménienne", "value": "AM", "flag": "🇦🇲" },
  { "label": "Australienne", "value": "AU", "flag": "🇦🇺" },
  { "label": "Autrichienne", "value": "AT", "flag": "🇦🇹" },
  { "label": "Azerbaïdjanaise", "value": "AZ", "flag": "🇦🇿" },

  { "label": "Bahreïnienne", "value": "BH", "flag": "🇧🇭" },
  { "label": "Bangladaise", "value": "BD", "flag": "🇧🇩" },
  { "label": "Belge", "value": "BE", "flag": "🇧🇪" },
  { "label": "Bhoutanaise", "value": "BT", "flag": "🇧🇹" },
  { "label": "Biélorusse", "value": "BY", "flag": "🇧🇾" },
  { "label": "Bolivienne", "value": "BO", "flag": "🇧🇴" },
  { "label": "Bosnienne", "value": "BA", "flag": "🇧🇦" },
  { "label": "Botswanaise", "value": "BW", "flag": "🇧🇼" },
  { "label": "Brésilienne", "value": "BR", "flag": "🇧🇷" },
  { "label": "Britannique", "value": "GB", "flag": "🇬🇧" },
  { "label": "Bulgares", "value": "BG", "flag": "🇧🇬" },
  { "label": "Burundaise", "value": "BI", "flag": "🇧🇮" },

  { "label": "Cambodgienne", "value": "KH", "flag": "🇰🇭" },
  { "label": "Camerounaise", "value": "CM", "flag": "🇨🇲" },
  { "label": "Canadienne", "value": "CA", "flag": "🇨🇦" },
  { "label": "Centrafricaine", "value": "CF", "flag": "🇨🇫" },
  { "label": "Chilienne", "value": "CL", "flag": "🇨🇱" },
  { "label": "Chinoise", "value": "CN", "flag": "🇨🇳" },
  { "label": "Colombienne", "value": "CO", "flag": "🇨🇴" },
  { "label": "Comorienne", "value": "KM", "flag": "🇰🇲" },
  { "label": "Congolaise (Congo)", "value": "CG", "flag": "🇨🇬" },
  { "label": "Congolaise (RDC)", "value": "CD", "flag": "🇨🇩" },
  { "label": "Coréenne", "value": "KR", "flag": "🇰🇷" },
  { "label": "Croate", "value": "HR", "flag": "🇭🇷" },
  { "label": "Cubaine", "value": "CU", "flag": "🇨🇺" },

  { "label": "Danoise", "value": "DK", "flag": "🇩🇰" },
  { "label": "Djiboutienne", "value": "DJ", "flag": "🇩🇯" },
  { "label": "Dominicaine", "value": "DO", "flag": "🇩🇴" },

  { "label": "Égyptienne", "value": "EG", "flag": "🇪🇬" },
  { "label": "Émiratie", "value": "AE", "flag": "🇦🇪" },
  { "label": "Équato-guinéenne", "value": "GQ", "flag": "🇬🇶" },
  { "label": "Équatorienne", "value": "EC", "flag": "🇪🇨" },
  { "label": "Espagnole", "value": "ES", "flag": "🇪🇸" },
  { "label": "Estonienne", "value": "EE", "flag": "🇪🇪" },
  { "label": "Éthiopienne", "value": "ET", "flag": "🇪🇹" },

  { "label": "Finlandaise", "value": "FI", "flag": "🇫🇮" },
  { "label": "Française", "value": "FR", "flag": "🇫🇷" },

  { "label": "Gabonaise", "value": "GA", "flag": "🇬🇦" },
  { "label": "Guatémaltèque", "value": "GT", "flag": "🇬🇹" },

  { "label": "Haïtienne", "value": "HT", "flag": "🇭🇹" },
  { "label": "Hondurienne", "value": "HN", "flag": "🇭🇳" },
  { "label": "Hongroise", "value": "HU", "flag": "🇭🇺" },

  { "label": "Indienne", "value": "IN", "flag": "🇮🇳" },
  { "label": "Indonésienne", "value": "ID", "flag": "🇮🇩" },
  { "label": "Irakienne", "value": "IQ", "flag": "🇮🇶" },
  { "label": "Iranienne", "value": "IR", "flag": "🇮🇷" },
  { "label": "Irlandaise", "value": "IE", "flag": "🇮🇪" },
  { "label": "Islandaise", "value": "IS", "flag": "🇮🇸" },
  { "label": "Israélienne", "value": "IL", "flag": "🇮🇱" },
  { "label": "Italienne", "value": "IT", "flag": "🇮🇹" },

  { "label": "Jamaïcaine", "value": "JM", "flag": "🇯🇲" },
  { "label": "Japonaise", "value": "JP", "flag": "🇯🇵" },
  { "label": "Jordanienne", "value": "JO", "flag": "🇯🇴" },

  { "label": "Kazakh", "value": "KZ", "flag": "🇰🇿" },
  { "label": "Kényane", "value": "KE", "flag": "🇰🇪" },
  { "label": "Kirghize", "value": "KG", "flag": "🇰🇬" },
  { "label": "Koweïtienne", "value": "KW", "flag": "🇰🇼" },

  { "label": "Laotienne", "value": "LA", "flag": "🇱🇦" },
  { "label": "Lettonne", "value": "LV", "flag": "🇱🇻" },
  { "label": "Libanaise", "value": "LB", "flag": "🇱🇧" },
  { "label": "Libyenne", "value": "LY", "flag": "🇱🇾" },
  { "label": "Lituanienne", "value": "LT", "flag": "🇱🇹" },
  { "label": "Luxembourgeoise", "value": "LU", "flag": "🇱🇺" },

  { "label": "Malaisienne", "value": "MY", "flag": "🇲🇾" },
  { "label": "Malawite", "value": "MW", "flag": "🇲🇼" },
  { "label": "Marocaine", "value": "MA", "flag": "🇲🇦" },
  { "label": "Mauricienne", "value": "MU", "flag": "🇲🇺" },
  { "label": "Mexicaine", "value": "MX", "flag": "🇲🇽" },
  { "label": "Mozambicaine", "value": "MZ", "flag": "🇲🇿" },

  { "label": "Néerlandaise", "value": "NL", "flag": "🇳🇱" },
  { "label": "Norvégienne", "value": "NO", "flag": "🇳🇴" },
  { "label": "Néo-zélandaise", "value": "NZ", "flag": "🇳🇿" },

  { "label": "Pakistanaise", "value": "PK", "flag": "🇵🇰" },
  { "label": "Palestinienne", "value": "PS", "flag": "🇵🇸" },
  { "label": "Panaméenne", "value": "PA", "flag": "🇵🇦" },
  { "label": "Paraguayenne", "value": "PY", "flag": "🇵🇾" },
  { "label": "Péruvienne", "value": "PE", "flag": "🇵🇪" },
  { "label": "Philippine", "value": "PH", "flag": "🇵🇭" },
  { "label": "Polonaise", "value": "PL", "flag": "🇵🇱" },
  { "label": "Portugaise", "value": "PT", "flag": "🇵🇹" },

  { "label": "Qatarie", "value": "QA", "flag": "🇶🇦" },

  { "label": "Roumaine", "value": "RO", "flag": "🇷🇴" },
  { "label": "Russe", "value": "RU", "flag": "🇷🇺" },
  { "label": "Rwandaise", "value": "RW", "flag": "🇷🇼" },

  { "label": "Saoudienne", "value": "SA", "flag": "🇸🇦" },
  { "label": "Serbe", "value": "RS", "flag": "🇷🇸" },
  { "label": "Singapourienne", "value": "SG", "flag": "🇸🇬" },
  { "label": "Slovaque", "value": "SK", "flag": "🇸🇰" },
  { "label": "Slovène", "value": "SI", "flag": "🇸🇮" },
  { "label": "Somalienne", "value": "SO", "flag": "🇸🇴" },
  { "label": "Sud-africaine", "value": "ZA", "flag": "🇿🇦" },
  { "label": "Sud-soudanaise", "value": "SS", "flag": "🇸🇸" },
  { "label": "Soudanaise", "value": "SD", "flag": "🇸🇩" },
  { "label": "Suédoise", "value": "SE", "flag": "🇸🇪" },
  { "label": "Suisse", "value": "CH", "flag": "🇨🇭" },
  { "label": "Syrienne", "value": "SY", "flag": "🇸🇾" },

  { "label": "Tanzanienne", "value": "TZ", "flag": "🇹🇿" },
  { "label": "Tchadienne", "value": "TD", "flag": "🇹🇩" },
  { "label": "Tchèque", "value": "CZ", "flag": "🇨🇿" },
  { "label": "Thaïlandaise", "value": "TH", "flag": "🇹🇭" },
  { "label": "Tunisienne", "value": "TN", "flag": "🇹🇳" },
  { "label": "Turkmène", "value": "TM", "flag": "🇹🇲" },
  { "label": "Turque", "value": "TR", "flag": "🇹🇷" },

  { "label": "Ukrainienne", "value": "UA", "flag": "🇺🇦" },
  { "label": "Uruguayenne", "value": "UY", "flag": "🇺🇾" },
  { "label": "Ougandaise", "value": "UG", "flag": "🇺🇬" },

  { "label": "Vénézuélienne", "value": "VE", "flag": "🇻🇪" },
  { "label": "Vietnamienne", "value": "VN", "flag": "🇻🇳" },

  { "label": "Zambienne", "value": "ZM", "flag": "🇿🇲" },
  { "label": "Zimbabwéenne", "value": "ZW", "flag": "🇿🇼" }
]
export const Indicatifs = [
  // --- AFRIQUE DE L’OUEST EN PREMIER ---
  { "label": "Côte d'Ivoire", "value": "+225", "flag": "🇨🇮" },
  { "label": "Mali", "value": "+223", "flag": "🇲🇱" },
  { "label": "Bénin", "value": "+229", "flag": "🇧🇯" },
  { "label": "Burkina Faso", "value": "+226", "flag": "🇧🇫" },
  { "label": "Cap-Vert", "value": "+238", "flag": "🇨🇻" },
  { "label": "Gambie", "value": "+220", "flag": "🇬🇲" },
  { "label": "Ghana", "value": "+233", "flag": "🇬🇭" },
  { "label": "Guinée", "value": "+224", "flag": "🇬🇳" },
  { "label": "Guinée-Bissau", "value": "+245", "flag": "🇬🇼" },
  { "label": "Libéria", "value": "+231", "flag": "🇱🇷" },
  { "label": "Mauritanie", "value": "+222", "flag": "🇲🇷" },
  { "label": "Niger", "value": "+227", "flag": "🇳🇪" },
  { "label": "Nigéria", "value": "+234", "flag": "🇳🇬" },
  { "label": "Sénégal", "value": "+221", "flag": "🇸🇳" },
  { "label": "Sierra Leone", "value": "+232", "flag": "🇸🇱" },
  { "label": "Togo", "value": "+228", "flag": "🇹🇬" },

  // --- RESTE DU MONDE (tri alphabétique) ---
  { "label": "Afghanistan", "value": "+93", "flag": "🇦🇫" },
  { "label": "Albanie", "value": "+355", "flag": "🇦🇱" },
  { "label": "Algérie", "value": "+213", "flag": "🇩🇿" },
  { "label": "Allemagne", "value": "+49", "flag": "🇩🇪" },
  { "label": "Andorre", "value": "+376", "flag": "🇦🇩" },
  { "label": "Angola", "value": "+244", "flag": "🇦🇴" },
  { "label": "Arabie Saoudite", "value": "+966", "flag": "🇸🇦" },
  { "label": "Argentine", "value": "+54", "flag": "🇦🇷" },
  { "label": "Arménie", "value": "+374", "flag": "🇦🇲" },
  { "label": "Australie", "value": "+61", "flag": "🇦🇺" },
  { "label": "Autriche", "value": "+43", "flag": "🇦🇹" },
  { "label": "Belgique", "value": "+32", "flag": "🇧🇪" },
  { "label": "Brésil", "value": "+55", "flag": "🇧🇷" },
  { "label": "Canada", "value": "+1", "flag": "🇨🇦" },
  { "label": "Chine", "value": "+86", "flag": "🇨🇳" },
  { "label": "Colombie", "value": "+57", "flag": "🇨🇴" },
  { "label": "Corée du Sud", "value": "+82", "flag": "🇰🇷" },
  { "label": "Danemark", "value": "+45", "flag": "🇩🇰" },
  { "label": "Égypte", "value": "+20", "flag": "🇪🇬" },
  { "label": "Espagne", "value": "+34", "flag": "🇪🇸" },
  { "label": "États-Unis", "value": "+1", "flag": "🇺🇸" },
  { "label": "Éthiopie", "value": "+251", "flag": "🇪🇹" },
  { "label": "Finlande", "value": "+358", "flag": "🇫🇮" },
  { "label": "France", "value": "+33", "flag": "🇫🇷" },
  { "label": "Géorgie", "value": "+995", "flag": "🇬🇪" },
  { "label": "Grèce", "value": "+30", "flag": "🇬🇷" },
  { "label": "Inde", "value": "+91", "flag": "🇮🇳" },
  { "label": "Indonésie", "value": "+62", "flag": "🇮🇩" },
  { "label": "Irlande", "value": "+353", "flag": "🇮🇪" },
  { "label": "Islande", "value": "+354", "flag": "🇮🇸" },
  { "label": "Italie", "value": "+39", "flag": "🇮🇹" },
  { "label": "Japon", "value": "+81", "flag": "🇯🇵" },
  { "label": "Kenya", "value": "+254", "flag": "🇰🇪" },
  { "label": "Liban", "value": "+961", "flag": "🇱🇧" },
  { "label": "Luxembourg", "value": "+352", "flag": "🇱🇺" },
  { "label": "Madagascar", "value": "+261", "flag": "🇲🇬" },
  { "label": "Maroc", "value": "+212", "flag": "🇲🇦" },
  { "label": "Mexique", "value": "+52", "flag": "🇲🇽" },
  { "label": "Norvège", "value": "+47", "flag": "🇳🇴" },
  { "label": "Pays-Bas", "value": "+31", "flag": "🇳🇱" },
  { "label": "Portugal", "value": "+351", "flag": "🇵🇹" },
  { "label": "Qatar", "value": "+974", "flag": "🇶🇦" },
  { "label": "Royaume-Uni", "value": "+44", "flag": "🇬🇧" },
  { "label": "Suisse", "value": "+41", "flag": "🇨🇭" },
  { "label": "Suède", "value": "+46", "flag": "🇸🇪" },
  { "label": "Tunisie", "value": "+216", "flag": "🇹🇳" },
  { "label": "Turquie", "value": "+90", "flag": "🇹🇷" }
]